inherit_gem:
  rubocop-rails-omakase: rubocop.yml

AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - vendor/**/*
    - Gemfile.lock
    - db/*_schema.rb
    - db/schema.rb
    - tmp/**/*
    - bin/**/*
    - test/dummy/**/*
    - bench/**/*
    - test/lib/action_cable/subscription_adapter/solid_cable_test.rb
    - lib/generators/**/*_schema.rb
  TargetRubyVersion: 3.3
