service: solidcable
image: npezza/solid_cable
asset_path: /rails/public/assets
servers:
  web:
    - <%= ENV["HOST"] %>
registry:
  username: npezza
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY
    - MYSQL_ROOT_PASSWORD
    - HOST

volumes:
  - "solidcable:/data"
builder:
  context: "."
  local:
    arch: amd64

accessories:
  mysql:
    image: mysql:8.3
    host: "<%= ENV['HOST'] %>"
    port: 3306
    env:
      clear:
        MYSQL_ROOT_HOST: '%'
      secret:
        - MYSQL_ROOT_PASSWORD
    files:
      - config/init.sql:/docker-entrypoint-initdb.d/setup.sql
    directories:
      - data:/var/lib/mysql
  redis:
    image: redis:latest
    host: "<%= ENV['HOST'] %>"
    port: 6379
    cmd: "redis-server"
    volumes:
      - /var/lib/redis:/data
